from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Protocol

from ..domain import EntityRevision, FileRevision, RepoCoreBlock, RepoEvent


class RepoMemoryStore(Protocol):
    def upsert_file_revision(self, revision: FileRevision) -> None: ...
    def upsert_entity_revision(self, revision: EntityRevision) -> None: ...
    def append_repo_event(self, event: RepoEvent) -> None: ...
    def list_repo_events(self, repo: str) -> Sequence[RepoEvent]: ...
    def set_core_block(self, repo: str, block: RepoCoreBlock) -> None: ...
    def list_core_blocks(self, repo: str) -> Sequence[RepoCoreBlock]: ...
    def record_lineage(
        self, entity_id: str, predecessor_id: str, reason: str, confidence: float
    ) -> None: ...
    def iter_entities(self, repo: str) -> Iterable[EntityRevision]: ...
