from __future__ import annotations

from collections.abc import Iterable, Sequence
from datetime import datetime
from typing import Protocol

from ..domain import (
    ClaimEvidence,
    ClaimKind,
    ClaimScopeKind,
    ClaimStatus,
    DreamRun,
    EntityRevision,
    FileRevision,
    MemoryClaim,
    RepoCoreBlock,
    RepoCoreSnapshot,
    RepoEvent,
)


class RepoMemoryStore(Protocol):
    def list_repositories(self) -> Sequence[str]: ...
    def upsert_file_revision(self, revision: FileRevision) -> None: ...
    def upsert_entity_revision(self, revision: EntityRevision) -> None: ...
    def append_repo_event(self, event: RepoEvent) -> None: ...
    def list_repo_events(self, repo: str) -> Sequence[RepoEvent]: ...
    def set_core_block(self, repo: str, block: RepoCoreBlock) -> None: ...
    def list_core_blocks(self, repo: str) -> Sequence[RepoCoreBlock]: ...
    def record_lineage(
        self, entity_id: str, predecessor_id: str, reason: str, confidence: float
    ) -> None: ...
    def iter_entities(self, repo: str) -> Iterable[EntityRevision]: ...
    def upsert_claim(self, claim: MemoryClaim) -> MemoryClaim: ...
    def get_claim_by_source_identity(self, repo: str, source_identity_key: str) -> MemoryClaim | None: ...
    def list_claims(
        self,
        repo: str,
        statuses: set[ClaimStatus] | None = None,
    ) -> Sequence[MemoryClaim]: ...
    def attach_claim_evidence(self, claim_key: str, evidence: ClaimEvidence) -> None: ...
    def list_claim_evidence(self, repo: str, claim_key: str) -> Sequence[ClaimEvidence]: ...
    def find_related_claims(
        self,
        repo: str,
        query_embedding: Sequence[float],
        *,
        claim_kind: ClaimKind | None = None,
        scope_kind: ClaimScopeKind | None = None,
        scope_ref: str | None = None,
        limit: int = 5,
    ) -> Sequence[tuple[MemoryClaim, float]]: ...
    def create_repo_core_snapshot(self, snapshot: RepoCoreSnapshot) -> None: ...
    def get_latest_repo_core_snapshot(self, repo: str) -> RepoCoreSnapshot | None: ...
    def create_dream_run(self, run: DreamRun) -> None: ...
    def finalize_dream_run(self, run: DreamRun) -> None: ...
    def acquire_dreaming_lease(
        self,
        repo: str,
        worker_id: str,
        now: datetime,
        ttl_seconds: int,
    ) -> bool: ...
    def release_dreaming_lease(self, repo: str, worker_id: str) -> None: ...
    def get_dreaming_cursor(self, repo: str) -> int: ...
    def set_dreaming_cursor(self, repo: str, watermark: int) -> None: ...
